export default [
  ['grać', 'spielen', 'spielte', 'gespielt'],
  ['mieszkać', 'wohnen', 'wohnte', 'gewohnt'],
  ['malować', 'malen', 'malte', 'gemalt'],
  ['płakać', 'weinen', 'weinte', 'geweint'],
  ['pytać', 'fragen', 'fragte', 'gefragt'],
  ['robić', 'machen', 'machte', 'gemacht'],
  ['ćwiczyć', 'üben', 'übte', 'geübt'],
  ['parkować', 'parken', 'parkte', 'geparkt'],
  ['śmiać się', 'lachen', 'lachte', 'gelacht'],
  ['słuchać', 'hören', 'hörte', 'gehört'],
  ['fotografować', 'fotografieren', 'fotografierte', 'gefotografiert'],
  ['zamawiać', 'bestellen', 'bestellte', 'gebestellt'],
  ['żyć', 'leben', 'lebte', 'gelebt'],
  ['czyścić', 'putzen', 'putzte', 'geputzt'],
  ['szukać', 'suchen', 'suchte', 'gesucht'],
  ['budować', 'bauen', 'baute', 'gebaut'],
  ['pokazywać', 'zeigen', 'zeigte', 'zeigt'],
  ['wybierać', 'wählen', 'wählte', 'gewählt'],
  ['wręczać', 'schenken', 'schenkte', 'geschenkt'],
  ['kochać', 'lieben', 'liebte', 'geliebt'],
  ['produkować', 'produzieren', 'produzierte', 'geproduziert'],
  ['odbierać', 'apholen', 'holte ap', 'apgeholt'],
  ['obchodzić, świętować', 'feiern', 'feiernte', 'gefeiernt'],
  ['zarabiać', 'verdienen', 'verdiente', 'geverdient'],
];
