export default [
  ['piec, wypalać', 'backen', 'buk', 'gebacken'],
  ['zaczynać', 'beginnen', 'begann', 'begonnen'],
  ['uchronić, kryć', 'bergen', 'barg', 'geborgen'],
  ['oferować', 'bieten', 'bot', 'geboten'],
  ['wiązać, łączyć', 'binden', 'band', 'gebunden'],
  ['prosić', 'bitten', 'bat', 'gebeten'],
  ['zostawać', 'bleiben', 'blieb', 'geblieben'],
  ['piec, smażyć', 'braten', 'briet', 'gebraten'],
  ['łamać, kruszyć', 'brechen', 'brach', 'gebrochen'],
  ['palić się, płonąć', 'brennen', 'brannte', 'gebrannt'],
  ['przynosić', 'bringen', 'brachte', 'gebracht'],
  ['myśleć', 'denken', 'dachte', 'gedacht'],
  ['móc (mieć pozwolenie)', 'dürfen', 'durfte', 'gedurft'],
  ['polecać, rekomendować', 'empfehlen', 'empfahl', 'empfohlen'],
  ['decydować', 'entscheiden', 'entschied', 'entschieden'],
  ['jeść', 'essen', 'aß', 'gegessen'],
  ['jechać, zawieźć', 'fahren', 'fuhr', 'gefahren'],
  ['upadać, spadać', 'fallen', 'fiel', 'gefallen'],
  ['łapać', 'fangen', 'fing', 'gefangen'],
  ['znajdować', 'finden', 'fand', 'gefunden'],
  ['latać', 'fliegen', 'flog', 'geflogen'],
  ['płynąć, cieknąć', 'fließen', 'floß', 'geflossen'],
  ['rodzić', 'gebären', 'gebar', 'geboren'],
  ['dawać', 'geben', 'gab', 'gegeben'],
  ['chodzić', 'gehen', 'ging', 'gegangen'],
  ['udawać się, powieść się', 'gelingen', 'gelang', 'gelungen'],
  ['spożywać', 'genießen', 'genoß', 'genossen'],
  ['stać się dziać się', 'geschehen', 'geschah', 'geschehen'],
  ['wygrywać', 'gewinnen', 'gewann', 'gewonnen'],
  ['nalewać, lać', 'gießen', 'goß', 'gegossen'],
  ['wyrównywać', 'gleichen', 'glich', 'geglichen'],
  ['ślizgać się, szybować', 'gleiten', 'glitt', 'geglitten'],
  ['łapać, ujmować', 'greifen', 'griff', 'gegriffen'],
  ['mieć', 'haben', 'hatte', 'gehabt'],
  ['trzymać', 'halten', 'hielt', 'gehalten'],
  ['podnosić', 'heben', 'hob', 'gehoben'],
  ['nazywać się', 'heißen', 'hieß', 'geheißen'],
  ['pomagać', 'helfen', 'half', 'geholfen'],
  ['znać', 'kennen', 'kannte', 'gekannt'],
  ['przychodzić', 'kommen', 'kam', 'gekommen'],
  ['móc, umieć', 'können', 'konnte', 'gekonnt'],
  ['ładować', 'laden', 'lud', 'geladen'],
  ['pozwalać', 'lassen', 'ließ', 'gelassen'],
  ['biegać, pędzić', 'laufen', 'lief', 'gelaufen'],
  ['cierpieć', 'leiden', 'litt', 'gelitten'],
  ['pożyczać', 'leihen', 'lieh', 'geliehen'],
  ['czytać', 'lesen', 'las', 'gelesen'],
];
