export default [
  ['piec, wypalać', 'backen', 'buk', 'hat gebacken'],
  ['zaczynać', 'beginnen', 'begann', 'hat begonnen'],
  ['uchronić, kryć', 'bergen', 'barg', 'hat geborgen'],
  ['oferować', 'bieten', 'bot', 'hat geboten'],
  ['wiązać, łączyć', 'binden', 'band', 'hat gebunden'],
  ['prosić', 'bitten', 'bat', 'hat gebeten'],
  ['zostawać', 'bleiben', 'blieb', 'ist geblieben'],
  ['piec, smażyć', 'braten', 'briet', 'hat gebraten'],
  ['łamać, kruszyć', 'brechen', 'brach', 'hat gebrochen'],
  ['palić się, płonąć', 'brennen', 'brannte', 'hat gebrannt'],
  ['przynosić', 'bringen', 'brachte', 'hat gebracht'],
  ['myśleć', 'denken', 'dachte', 'hat gedacht'],
  ['móc (mieć pozwolenie)', 'dürfen', 'durfte', 'hat gedurft'],
  ['polecać, rekomendować', 'empfehlen', 'empfahl', 'hat empfohlen'],
  ['decydować', 'entscheiden', 'entschied', 'hat entschieden'],
  ['jeść', 'essen', 'aß', 'hat gegessen'],
  ['jechać, zawieźć', 'fahren', 'fuhr', 'ist/hat gefahren'],
  ['upadać, spadać', 'fallen', 'fiel', 'ist gefallen'],
  ['łapać', 'fangen', 'fing', 'hat gefangen'],
  ['znajdować', 'finden', 'fand', 'hat gefunden'],
  ['latać', 'fliegen', 'flog', 'ist geflogen'],
  ['płynąć, cieknąć', 'fließen', 'floß', 'ist geflossen'],
  ['rodzić', 'gebären', 'gebar', 'hat geboren'],
  ['dawać', 'geben', 'gab', 'hat gegeben'],
  ['chodzić', 'gehen', 'ging', 'ist gegangen'],
  ['udawać się, powieść się', 'gelingen', 'gelang', 'ist gelungen'],
  ['spożywać', 'genießen', 'genoß', 'hat genossen'],
  ['stać się dziać się', 'geschehen', 'geschah', 'ist geschehen'],
  ['wygrywać', 'gewinnen', 'gewann', 'hat gewonnen'],
  ['nalewać, lać', 'gießen', 'goß', 'hat gegossen'],
  ['wyrównywać', 'gleichen', 'glich', 'hat geglichen'],
  ['ślizgać się, szybować', 'gleiten', 'glitt', 'ist geglitten'],
  ['łapać, ujmować', 'greifen', 'griff', 'hat gegriffen'],
  ['mieć', 'haben', 'hatte', 'hat gehabt'],
  ['trzymać', 'halten', 'hielt', 'hat gehalten'],
  ['podnosić', 'heben', 'hob', 'hat gehobem'],
  ['nazywać się', 'heißen', 'hieß', 'hat geheißen'],
  ['pomagać', 'helfen', 'half', 'hat geholfen'],
  ['znać', 'kennen', 'kannte', 'hat gekannt'],
  ['przychodzić', 'kommen', 'kam', 'ist gekommen'],
  ['móc, umieć', 'können', 'konnte', 'hat gekonnt'],
  ['ładować', 'laden', 'lud', 'hat geladen'],
  ['pozwalać', 'lassen', 'ließ', 'hat gelassen'],
  ['biegać, pędzić', 'laufen', 'lief', 'ist gelaufen'],
  ['cierpieć', 'leiden', 'litt', 'hat gelitten'],
  ['pożyczać', 'leihen', 'lieh', 'hat geliehen'],
  ['czytać', 'lesen', 'las', 'hat gelesen'],
];
