//Słówka z zeszytu
export default [
  ['Odpowiadać', 'antworten', 'geantwortet'],
  ['Pracować', 'arbeiten', 'gearbeitet'],
  ['Sprzątać', 'aufräumen', 'aufgeräumt'],
  ['Zakończyć', 'beenden', 'beendt'],
  ['Szczekać', 'bellen', 'gebellt'],
  ['Zwiedzać/Oglądać', 'besichtigen', 'besichtigt'],
  ['Zamawiać', 'bestellen', 'bestellt'],
  ['Odwiedzać', 'besuchen', 'besucht'],
  ['Zapłacić', 'bezahle', 'bezahlt'],
  ['Brać prysznic', 'duschen', 'geduscht'],
  ['Kupować', 'kaufen', 'gekauft'],
  ['Pytać', 'fragen', 'gefragt'],
  ['Jeść śniadanie', 'frühstücken', 'gefrühstückt'],
  ['Funkcjonować', 'funktionieren', 'funktioniert'],
  ['Wierzyć', 'glauben', 'geglaubt'],
  ['Słuchać', 'hören', 'gehören'],
  ['Informować', 'informieren', 'informiert'],
  ['Gotować', 'kochen', 'gekocht'],
  ['Uczyć się', 'lernen', 'gelernt'],
  ['Robić', 'machen', 'gemacht'],
  ['Montować', 'montieren', 'montiert'],
  ['Otwierać', 'öffnen', 'geöffnet'],
  ['Pakować', 'packen', 'gepackt'],
  ['Palić papierosy', 'rauchen', 'geraucht'],
  ['Podróżować', 'reisen', 'gereist'],
  ['Rezerwować', 'reservieren', 'reserviert'],
  ['Smakować', 'schmecken', 'geschmeckt'],
  ['Grać', 'spielen', 'gespielt'],
  ['Studiować', 'studieren', 'studiert'],
  ['Dzwonić/Telefonować', 'telefonieren', 'telefoniert'],
  ['Szukać', 'suchen', 'gesucht'],
  ['Wędrować', 'bändern', 'gebändert'],
  ['Mieszkać', 'wohnen', 'gewohnt'],
  ['Płakać', 'weinen', 'geweint'],
  ['Pokazywać', 'zeigen', 'gezeigt'],
];
